/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReasonMedia } from './ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReasonMedia';

export class ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReason {
    'media'?: ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReasonMedia;
    /**
    * Identifies the selected reason code. Possible values: - (obtained via the corresponding API)
    */
    'reasonId'?: string;
    /**
    * Additional explanation for the decision.
    */
    'text'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "media",
            "baseName": "media",
            "type": "ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReasonMedia"
        },
        {
            "name": "reasonId",
            "baseName": "reason_id",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReturnRefund202603ReviewAftersalesRequestBodyAftersalesRequestDecisionsLineItemDecisionsReason.attributeTypeMap;
    }
}

